spring:
  config.activate.on-profile: default

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/todo-healthcare
    username: sa


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show-sql: trued
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace