--
-- 코드그룹 INSERT
--
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('성별코드' , '성별코드', '성별을 표시', NOW(), NULL, NOW());
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드' , '방문상태코드', '환자방문의 상태(방문중, 종료, 취소)', NOW(), NULL, NOW());
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료과목코드' , '진료과목코드', '진료과목(내과, 안과)', NOW(), NULL, NOW());
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료유형코드' , '진료유형코드', '진료의 유형(약처방, 검사 등)', NOW(), NULL, NOW());
--
-- 코드 INSERT
--
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('성별코드', 'M', '남', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('성별코드', 'F', '여', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드', '1', '방문중', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드', '2', '종료', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드', '3', '취소', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료과목코드', '01', '내과', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료과목코드', '02', '안과', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료유형코드', 'D', '약처방', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료유형코드', 'T', '검사', NOW(), NULL, NOW());
--
-- 병원 INSERT
--
INSERT INTO HOSPITAL(ID, NAME, CARE_CENTER_NO, DIRECTOR, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES(1, 'A병원', '01', 'A병원장', NOW(), NULL, NOW());
INSERT INTO HOSPITAL(ID, NAME, CARE_CENTER_NO, DIRECTOR, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES(2, 'B병원', '02', 'B병원장', NOW(), NULL, NOW());
