--
-- 코드그룹 INSERT
--
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('성별코드' , '성별코드', '성별을 표시', NOW(), NULL, NOW());
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드' , '방문상태코드', '환자방문의 상태(방문중, 종료, 취소)', NOW(), NULL, NOW());
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료과목코드' , '진료과목코드', '진료과목(내과, 안과)', NOW(), NULL, NOW());
INSERT INTO CODE_GROUP(CODE_GROUP, NAME, EXPLANATION, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료유형코드' , '진료유형코드', '진료의 유형(약처방, 검사 등)', NOW(), NULL, NOW());
--
-- 코드 INSERT
--
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('성별코드', 'M', '남', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('성별코드', 'F', '여', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드', '1', '방문중', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드', '2', '종료', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('방문상태코드', '3', '취소', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료과목코드', '01', '내과', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료과목코드', '02', '안과', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료유형코드', 'D', '약처방', NOW(), NULL, NOW());
INSERT INTO CODE(CODE_GROUP, CODE, NAME, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('진료유형코드', 'T', '검사', NOW(), NULL, NOW());
--
-- 병원 INSERT
--
INSERT INTO HOSPITAL(NAME, CARE_CENTER_NO, DIRECTOR, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('A병원', '01', 'A병원장', NOW(), NULL, NOW());
INSERT INTO HOSPITAL(NAME, CARE_CENTER_NO, DIRECTOR, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES('B병원', '02', 'B병원장', NOW(), NULL, NOW());
--
-- 환자 INSERT
--
INSERT INTO PATIENT (NAME, PHONE, BIRTH, GENDER, REGISTRATION_NO, HOSPITAL_ID, LAST_VISIT_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES ('환자A1', '010-1111-1111', '1990-01-01', 'M', '2023010001', 1, NULL, NOW(), NULL, NOW());
INSERT INTO PATIENT (NAME, PHONE, BIRTH, GENDER, REGISTRATION_NO, HOSPITAL_ID, LAST_VISIT_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES ('환자A2', '010-2222-2222', '1990-02-02', 'F', '2023010002', 1, NULL, NOW(), NULL, NOW());
INSERT INTO PATIENT (NAME, PHONE, BIRTH, GENDER, REGISTRATION_NO, HOSPITAL_ID, LAST_VISIT_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES ('환자B1', '010-3333-3333', '1990-03-03', 'F', '2023020001', 2, NULL, NOW(), NULL, NOW());
INSERT INTO PATIENT (NAME, PHONE, BIRTH, GENDER, REGISTRATION_NO, HOSPITAL_ID, LAST_VISIT_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES ('환자B2', '010-4444-4444', '1990-04-04', 'M', '2023020002', 2, NULL, NOW(), NULL, NOW());
--
-- 방문정보 INSERT, 환자 최종 방문일자 UPDATE
--
INSERT INTO VISIT(DEPARTMENT_CODE, TYPE_CODE, VISIT_STATE_CODE, HOSPITAL_ID, PATIENT_ID, RECEPTION_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES( '01', 'D', '1', '1', '1', NOW(), NOW(), NULL, NOW());
UPDATE PATIENT SET LAST_VISIT_DATE = NOW() WHERE ID = 1;
INSERT INTO VISIT(DEPARTMENT_CODE, TYPE_CODE, VISIT_STATE_CODE, HOSPITAL_ID, PATIENT_ID, RECEPTION_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES( '02', 'T', '3', '1', '2', NOW(), NOW(), NULL, NOW());
UPDATE PATIENT SET LAST_VISIT_DATE = NOW() WHERE ID = 2;
INSERT INTO VISIT(DEPARTMENT_CODE, TYPE_CODE, VISIT_STATE_CODE, HOSPITAL_ID, PATIENT_ID, RECEPTION_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES( '01', 'T', '3', '2', '1', NOW(), NOW(), NULL, NOW());
UPDATE PATIENT SET LAST_VISIT_DATE = NOW() WHERE ID = 3;
INSERT INTO VISIT(DEPARTMENT_CODE, TYPE_CODE, VISIT_STATE_CODE, HOSPITAL_ID, PATIENT_ID, RECEPTION_DATE, CREATED_DATE, DELETED_DATE, LAST_MODIFIED_DATE) VALUES( '02', 'D', '1', '2', '2', NOW(), NOW(), NULL, NOW());
UPDATE PATIENT SET LAST_VISIT_DATE = NOW() WHERE ID = 4;